import "./sass/main.scss";
import { openHamburgerMenu } from "./modules/hamburgerMenu.js";
import { changeIcons } from "./modules/changeIconFill";
import { openSidebar } from "./modules/toggleSidebar";
import { toggleProjects } from "./modules/toggleProjects";
import { projects, showProjectModal } from "./modules/projectModal";
import { showTaskModal, populateProjectsForTask } from "./modules/taskModal";
import { populateContent } from "./modules/populateMainContent";
import { populateProjectsList } from "./modules/projectModal";
openHamburgerMenu();
changeIcons();
openSidebar();
toggleProjects();
showProjectModal();
showTaskModal();
populateContent();
populateProjectsList();
populateProjectsForTask();
