import "./sass/main.scss";
import toggles from "./modules/toggles";
import { changeIcons } from "./modules/changeIconFill";
import { showProjectModal } from "./modules/projectModal";
import { showTaskModal, populateProjectsForTask } from "./modules/taskModal";
import { onLoadPopulate } from "./modules/populateMainContent";
import { populateProjectsList } from "./modules/projectModal";
toggles();
changeIcons();
showProjectModal();
showTaskModal();
onLoadPopulate();
populateProjectsList();
populateProjectsForTask();
